### ISSUE TITLE
Forcing https breaks most local gateways

### ISSUE THREAD

**Issue by ReveredOxygen** [aboutDavid/p2pbin#3]
[Here](https://github.com/aboutDavid/p2pbin/blob/9e20721621ff2da3ce34201b9b3b492aecb77b1a/index.html#L93), it forces it to switch to https no matter what. However, as most people run their local gateway on port 8080, this doesn't work and instead blocks you from connecting. This should either be removed or first check that it's on a port that supports https.

**Comment by aboutDavid** [comment]
#4 Fixes this.
